version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - "27017:2701"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: 'mongo-express'
    ports:
      - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
  frontend:
    image: 'elisaflemer/narutofrontend:latest'
    ports:
      - "80:5173"
    depends_on:
      - backend
  backend:
    image: 'elisaflemer/narutobackend:latest'
    ports:
      - "5000:5000"
    depends_on:
      - mongo